### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by vasily-mancanweb** [mijora/omniva-prestahop-1.7#32]
Hi, first of all, a big thank you for your plugin. I met such problem that I can't install it. When I try to upload it with the plugin installer it shows me an error "Šis failas yra negaliojantis modulio zip failas". I tried to upload it manually with FTP but Presta doesn't see it. On the server no errors. My Prestashop version is 1.7.7.7 and the plugin version is 1.1.7. Could you help to identify where is a problem?
Thank you

**Comment by vasily-mancanweb** [comment]
Hi, do you have any news?

**Comment by LithMage** [comment]
Are you sure you are uploading omnivaltshipping.zip fie downloaded from releases here on github? If uploading manualy (omnivaltshipping folder into modules folder of prestashop) in order to install it you need to then find it in prestshop module manager (the second option in admin, not the one where installed modules list is)

**Comment by vasily-mancanweb** [comment]
Thank you for your quick response. I think there was a problem with other addons.
